// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package registrydb

type AssetBinding struct {
	AssetID      string
	PrincipalID  string
	CredentialID string
	Verifier     []byte
	Active       bool
	Revoked      bool
}

type EnrollmentAuthority struct {
	Singleton int64
	Verifier  []byte
	Revoked   bool
}

type ManagementSecret struct {
	Singleton int64
	Verifier  []byte
}

type OperatorKey struct {
	ID        string
	Verifier  []byte
	CreatedAt int64
	Revoked   bool
}

type Plugin struct {
	ID             string
	Release        string
	Endpoint       string
	DispatchSecret string
	InstalledAt    int64
}

type PluginCapability struct {
	PluginID    string
	Name        string
	InputSchema string
}

type PluginKey struct {
	PluginID string
	Verifier []byte
	Revoked  bool
}
