// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package registrydb

import (
	"context"
)

const createCapability = `-- name: CreateCapability :exec
INSERT INTO plugin_capabilities (plugin_id, name, input_schema) VALUES (?, ?, ?)
`

type CreateCapabilityParams struct {
	PluginID    string
	Name        string
	InputSchema string
}

func (q *Queries) CreateCapability(ctx context.Context, arg CreateCapabilityParams) error {
	_, err := q.db.ExecContext(ctx, createCapability, arg.PluginID, arg.Name, arg.InputSchema)
	return err
}

const createPlugin = `-- name: CreatePlugin :exec
INSERT INTO plugins (id, release, endpoint, dispatch_secret, installed_at) VALUES (?, ?, ?, ?, ?)
`

type CreatePluginParams struct {
	ID             string
	Release        string
	Endpoint       string
	DispatchSecret string
	InstalledAt    int64
}

func (q *Queries) CreatePlugin(ctx context.Context, arg CreatePluginParams) error {
	_, err := q.db.ExecContext(ctx, createPlugin,
		arg.ID,
		arg.Release,
		arg.Endpoint,
		arg.DispatchSecret,
		arg.InstalledAt,
	)
	return err
}

const getCapability = `-- name: GetCapability :one
SELECT plugin_id, name, input_schema FROM plugin_capabilities WHERE plugin_id = ? AND name = ?
`

type GetCapabilityParams struct {
	PluginID string
	Name     string
}

func (q *Queries) GetCapability(ctx context.Context, arg GetCapabilityParams) (PluginCapability, error) {
	row := q.db.QueryRowContext(ctx, getCapability, arg.PluginID, arg.Name)
	var i PluginCapability
	err := row.Scan(&i.PluginID, &i.Name, &i.InputSchema)
	return i, err
}

const getPlugin = `-- name: GetPlugin :one
SELECT id, "release", endpoint, dispatch_secret, installed_at FROM plugins WHERE id = ?
`

func (q *Queries) GetPlugin(ctx context.Context, id string) (Plugin, error) {
	row := q.db.QueryRowContext(ctx, getPlugin, id)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Release,
		&i.Endpoint,
		&i.DispatchSecret,
		&i.InstalledAt,
	)
	return i, err
}

const listAllPlugins = `-- name: ListAllPlugins :many
SELECT id, "release", endpoint, dispatch_secret, installed_at FROM plugins ORDER BY id
`

func (q *Queries) ListAllPlugins(ctx context.Context) ([]Plugin, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plugin
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.Release,
			&i.Endpoint,
			&i.DispatchSecret,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapabilities = `-- name: ListCapabilities :many
SELECT plugin_id, name, input_schema FROM plugin_capabilities WHERE plugin_id = ? ORDER BY name
`

func (q *Queries) ListCapabilities(ctx context.Context, pluginID string) ([]PluginCapability, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilities, pluginID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginCapability
	for rows.Next() {
		var i PluginCapability
		if err := rows.Scan(&i.PluginID, &i.Name, &i.InputSchema); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginsAfter = `-- name: ListPluginsAfter :many
SELECT id, "release", endpoint, dispatch_secret, installed_at FROM plugins WHERE id > ? ORDER BY id LIMIT ?
`

type ListPluginsAfterParams struct {
	ID    string
	Limit int64
}

func (q *Queries) ListPluginsAfter(ctx context.Context, arg ListPluginsAfterParams) ([]Plugin, error) {
	rows, err := q.db.QueryContext(ctx, listPluginsAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plugin
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.Release,
			&i.Endpoint,
			&i.DispatchSecret,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
