//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AssetEnrollmentRequestKind.
const (
	AssetEnrollmentRequestKindAsset AssetEnrollmentRequestKind = "asset"
)

// Valid indicates whether the value is a known member of the AssetEnrollmentRequestKind enum.
func (e AssetEnrollmentRequestKind) Valid() bool {
	switch e {
	case AssetEnrollmentRequestKindAsset:
		return true
	default:
		return false
	}
}

// Defines values for AssetStatus.
const (
	AssetStatusBusy         AssetStatus = "busy"
	AssetStatusError        AssetStatus = "error"
	AssetStatusInitializing AssetStatus = "initializing"
	AssetStatusPaused       AssetStatus = "paused"
	AssetStatusReady        AssetStatus = "ready"
	AssetStatusStopped      AssetStatus = "stopped"
	AssetStatusUnknown      AssetStatus = "unknown"
)

// Valid indicates whether the value is a known member of the AssetStatus enum.
func (e AssetStatus) Valid() bool {
	switch e {
	case AssetStatusBusy:
		return true
	case AssetStatusError:
		return true
	case AssetStatusInitializing:
		return true
	case AssetStatusPaused:
		return true
	case AssetStatusReady:
		return true
	case AssetStatusStopped:
		return true
	case AssetStatusUnknown:
		return true
	default:
		return false
	}
}

// Defines values for CommandSupportScheduling.
const (
	Immediate CommandSupportScheduling = "immediate"
	Queued    CommandSupportScheduling = "queued"
)

// Valid indicates whether the value is a known member of the CommandSupportScheduling enum.
func (e CommandSupportScheduling) Valid() bool {
	switch e {
	case Immediate:
		return true
	case Queued:
		return true
	default:
		return false
	}
}

// Defines values for Communications.
const (
	Degraded      Communications = "degraded"
	Healthy       Communications = "healthy"
	HighBandwidth Communications = "high_bandwidth"
	Offline       Communications = "offline"
)

// Valid indicates whether the value is a known member of the Communications enum.
func (e Communications) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Healthy:
		return true
	case HighBandwidth:
		return true
	case Offline:
		return true
	default:
		return false
	}
}

// Defines values for DependencyStatus.
const (
	DependencyStatusReady       DependencyStatus = "ready"
	DependencyStatusUnavailable DependencyStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the DependencyStatus enum.
func (e DependencyStatus) Valid() bool {
	switch e {
	case DependencyStatusReady:
		return true
	case DependencyStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for EntityKind.
const (
	EntityKindAsset EntityKind = "asset"
)

// Valid indicates whether the value is a known member of the EntityKind enum.
func (e EntityKind) Valid() bool {
	switch e {
	case EntityKindAsset:
		return true
	default:
		return false
	}
}

// Defines values for EntityChangeKind.
const (
	Create EntityChangeKind = "create"
	Update EntityChangeKind = "update"
)

// Valid indicates whether the value is a known member of the EntityChangeKind enum.
func (e EntityChangeKind) Valid() bool {
	switch e {
	case Create:
		return true
	case Update:
		return true
	default:
		return false
	}
}

// Defines values for EntityChangeResourceType.
const (
	EntityChangeResourceTypeEntity EntityChangeResourceType = "entity"
)

// Valid indicates whether the value is a known member of the EntityChangeResourceType enum.
func (e EntityChangeResourceType) Valid() bool {
	switch e {
	case EntityChangeResourceTypeEntity:
		return true
	default:
		return false
	}
}

// Defines values for FeedChangeType.
const (
	Change FeedChangeType = "change"
)

// Valid indicates whether the value is a known member of the FeedChangeType enum.
func (e FeedChangeType) Valid() bool {
	switch e {
	case Change:
		return true
	default:
		return false
	}
}

// Defines values for FeedGapCode.
const (
	FeedGapCodeCursorExpired FeedGapCode = "cursor_expired"
)

// Valid indicates whether the value is a known member of the FeedGapCode enum.
func (e FeedGapCode) Valid() bool {
	switch e {
	case FeedGapCodeCursorExpired:
		return true
	default:
		return false
	}
}

// Defines values for FeedGapType.
const (
	Gap FeedGapType = "gap"
)

// Valid indicates whether the value is a known member of the FeedGapType enum.
func (e FeedGapType) Valid() bool {
	switch e {
	case Gap:
		return true
	default:
		return false
	}
}

// Defines values for FeedHelloType.
const (
	Hello FeedHelloType = "hello"
)

// Valid indicates whether the value is a known member of the FeedHelloType enum.
func (e FeedHelloType) Valid() bool {
	switch e {
	case Hello:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Alive HealthStatus = "alive"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Alive:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	ReadinessStatusReady       ReadinessStatus = "ready"
	ReadinessStatusUnavailable ReadinessStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case ReadinessStatusReady:
		return true
	case ReadinessStatusUnavailable:
		return true
	default:
		return false
	}
}

// AssetCommunicationsComponent defines model for AssetCommunicationsComponent.
type AssetCommunicationsComponent struct {
	LinkState Communications `json:"link_state"`
}

// AssetComponentPatch defines model for AssetComponentPatch.
type AssetComponentPatch struct {
	// Health Replaces stored health; null clears it.
	Health nullable.Nullable[AssetHealthPatch] `json:"health,omitempty"`
	Status *AssetInitialStatus                 `json:"status,omitempty"`

	// Telemetry Present fields replace stored values and null clears a field; null
	// for the whole component clears all telemetry. After merging,
	// latitude and longitude must be both present or both absent.
	Telemetry nullable.Nullable[AssetTelemetryPatch] `json:"telemetry,omitempty"`
}

// AssetComponents defines model for AssetComponents.
type AssetComponents struct {
	Communications AssetCommunicationsComponent `json:"communications"`
	Health         *AssetHealthComponent        `json:"health,omitempty"`
	Heartbeat      AssetHeartbeatComponent      `json:"heartbeat"`
	Status         AssetStatusComponent         `json:"status"`

	// Telemetry Latitude and longitude are supplied together.
	Telemetry *AssetTelemetryComponent `json:"telemetry,omitempty"`
}

// AssetEnrollmentRequest defines model for AssetEnrollmentRequest.
type AssetEnrollmentRequest struct {
	// Alias Unique across Entities, ignoring case.
	Alias           *string                 `json:"alias,omitempty"`
	CommandManifest *[]CommandSupport       `json:"command_manifest,omitempty"`
	Components      *AssetInitialComponents `json:"components,omitempty"`

	// Credential The Asset's own credential, prepared and retained by the SDK before the first attempt.
	Credential string                     `json:"credential"`
	DatasetId  openapi_types.UUID         `json:"dataset_id"`
	Id         openapi_types.UUID         `json:"id"`
	Kind       AssetEnrollmentRequestKind `json:"kind"`
	RequestId  openapi_types.UUID         `json:"request_id"`
	Subtype    *string                    `json:"subtype,omitempty"`
}

// AssetEnrollmentRequestKind defines model for AssetEnrollmentRequest.Kind.
type AssetEnrollmentRequestKind string

// AssetEnrollmentResult defines model for AssetEnrollmentResult.
type AssetEnrollmentResult struct {
	Asset        Entity             `json:"asset"`
	CredentialId openapi_types.UUID `json:"credential_id"`
	PrincipalId  openapi_types.UUID `json:"principal_id"`
}

// AssetHealthComponent defines model for AssetHealthComponent.
type AssetHealthComponent struct {
	BatteryPercent float64 `json:"battery_percent"`
}

// AssetHealthPatch Replaces stored health; null clears it.
type AssetHealthPatch struct {
	BatteryPercent float64 `json:"battery_percent"`
}

// AssetHeartbeatComponent defines model for AssetHeartbeatComponent.
type AssetHeartbeatComponent struct {
	LastSeen nullable.Nullable[time.Time] `json:"last_seen"`
}

// AssetInitialComponents defines model for AssetInitialComponents.
type AssetInitialComponents struct {
	Health *AssetHealthComponent `json:"health,omitempty"`
	Status *AssetInitialStatus   `json:"status,omitempty"`

	// Telemetry Latitude and longitude are supplied together.
	Telemetry *AssetTelemetryComponent `json:"telemetry,omitempty"`
}

// AssetInitialStatus defines model for AssetInitialStatus.
type AssetInitialStatus struct {
	Value AssetStatus `json:"value"`
}

// AssetReport One Asset-originated change. A fresh report records contact even with
// no components. Reports apply in increasing sequence order; resending a
// report ID with the same facts returns the current Entity. Present
// components merge into stored ones (see each patch schema);
// `command_manifest` replaces the stored manifest.
type AssetReport struct {
	CommandManifest *[]CommandSupport    `json:"command_manifest,omitempty"`
	Components      *AssetComponentPatch `json:"components,omitempty"`
	DatasetId       openapi_types.UUID   `json:"dataset_id"`
	ReportId        openapi_types.UUID   `json:"report_id"`
	Sequence        int64                `json:"sequence"`
}

// AssetStatus defines model for AssetStatus.
type AssetStatus string

// AssetStatusComponent defines model for AssetStatusComponent.
type AssetStatusComponent struct {
	// ReportedAt When Core accepted the latest status report; null until the Asset reports status.
	ReportedAt nullable.Nullable[time.Time] `json:"reported_at"`
	Value      AssetStatus                  `json:"value"`
}

// AssetStatusReport defines model for AssetStatusReport.
type AssetStatusReport struct {
	DatasetId openapi_types.UUID `json:"dataset_id"`
	ReportId  openapi_types.UUID `json:"report_id"`
	Sequence  int64              `json:"sequence"`
	Status    AssetStatus        `json:"status"`
}

// AssetStatusView defines model for AssetStatusView.
type AssetStatusView struct {
	Communications AssetCommunicationsComponent `json:"communications"`
	Heartbeat      AssetHeartbeatComponent      `json:"heartbeat"`
	Status         AssetStatusComponent         `json:"status"`
}

// AssetTelemetryComponent Latitude and longitude are supplied together.
type AssetTelemetryComponent struct {
	AltitudeM  *float64 `json:"altitude_m,omitempty"`
	HeadingDeg *float64 `json:"heading_deg,omitempty"`
	Latitude   *float64 `json:"latitude,omitempty"`
	Longitude  *float64 `json:"longitude,omitempty"`
	SpeedMps   *float64 `json:"speed_mps,omitempty"`
}

// AssetTelemetryPatch Present fields replace stored values and null clears a field; null
// for the whole component clears all telemetry. After merging,
// latitude and longitude must be both present or both absent.
type AssetTelemetryPatch struct {
	AltitudeM  nullable.Nullable[float64] `json:"altitude_m,omitempty"`
	HeadingDeg nullable.Nullable[float64] `json:"heading_deg,omitempty"`
	Latitude   nullable.Nullable[float64] `json:"latitude,omitempty"`
	Longitude  nullable.Nullable[float64] `json:"longitude,omitempty"`
	SpeedMps   nullable.Nullable[float64] `json:"speed_mps,omitempty"`
}

// ChangePage defines model for ChangePage.
type ChangePage struct {
	Changes []EntityChange `json:"changes"`

	// Cursor Cursor after the last returned change, or unchanged when there are none.
	Cursor    string             `json:"cursor"`
	DatasetId openapi_types.UUID `json:"dataset_id"`
}

// CommandSupport defines model for CommandSupport.
type CommandSupport struct {
	Cancellation *bool                      `json:"cancellation,omitempty"`
	CommandId    string                     `json:"command_id"`
	Description  *string                    `json:"description,omitempty"`
	Progress     *bool                      `json:"progress,omitempty"`
	Scheduling   []CommandSupportScheduling `json:"scheduling"`
}

// CommandSupportScheduling defines model for CommandSupport.Scheduling.
type CommandSupportScheduling string

// Communications defines model for Communications.
type Communications string

// Dataset defines model for Dataset.
type Dataset struct {
	Id             openapi_types.UUID `json:"id"`
	WritingRelease string             `json:"writing_release"`
}

// DependencyStatus defines model for DependencyStatus.
type DependencyStatus string

// Entity defines model for Entity.
type Entity struct {
	Alias nullable.Nullable[string] `json:"alias"`

	// ChangeSequence Sequence of the committed change that produced this state.
	ChangeSequence  int64                     `json:"change_sequence"`
	CommandManifest []CommandSupport          `json:"command_manifest"`
	Components      AssetComponents           `json:"components"`
	DatasetId       openapi_types.UUID        `json:"dataset_id"`
	Id              openapi_types.UUID        `json:"id"`
	Kind            EntityKind                `json:"kind"`
	Subtype         nullable.Nullable[string] `json:"subtype"`
	Version         int                       `json:"version"`
}

// EntityKind defines model for Entity.Kind.
type EntityKind string

// EntityChange defines model for EntityChange.
type EntityChange struct {
	DatasetId    openapi_types.UUID       `json:"dataset_id"`
	Entity       Entity                   `json:"entity"`
	Kind         EntityChangeKind         `json:"kind"`
	ResourceId   openapi_types.UUID       `json:"resource_id"`
	ResourceType EntityChangeResourceType `json:"resource_type"`
	Sequence     int64                    `json:"sequence"`
}

// EntityChangeKind defines model for EntityChange.Kind.
type EntityChangeKind string

// EntityChangeResourceType defines model for EntityChange.ResourceType.
type EntityChangeResourceType string

// EntityPage defines model for EntityPage.
type EntityPage struct {
	// Baseline Change cursor at the snapshot's baseline; replay from it after the last page.
	Baseline         string             `json:"baseline"`
	BaselineSequence int64              `json:"baseline_sequence"`
	DatasetId        openapi_types.UUID `json:"dataset_id"`
	Entities         []Entity           `json:"entities"`
	NextCursor       *string            `json:"next_cursor,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FeedAuthentication defines model for FeedAuthentication.
type FeedAuthentication struct {
	ApiKey string `json:"api_key"`
}

// FeedChange defines model for FeedChange.
type FeedChange struct {
	Change EntityChange `json:"change"`

	// Cursor Change cursor after this change.
	Cursor string         `json:"cursor"`
	Type   FeedChangeType `json:"type"`
}

// FeedChangeType defines model for FeedChange.Type.
type FeedChangeType string

// FeedGap defines model for FeedGap.
type FeedGap struct {
	Code FeedGapCode `json:"code"`
	Type FeedGapType `json:"type"`
}

// FeedGapCode defines model for FeedGap.Code.
type FeedGapCode string

// FeedGapType defines model for FeedGap.Type.
type FeedGapType string

// FeedHello defines model for FeedHello.
type FeedHello struct {
	// Cursor Change cursor at the subscription point; every later commit is delivered.
	Cursor    string             `json:"cursor"`
	DatasetId openapi_types.UUID `json:"dataset_id"`
	Sequence  int64              `json:"sequence"`
	Type      FeedHelloType      `json:"type"`
}

// FeedHelloType defines model for FeedHello.Type.
type FeedHelloType string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Readiness defines model for Readiness.
type Readiness struct {
	Dependencies struct {
		Objects DependencyStatus `json:"objects"`
		Sqlite  DependencyStatus `json:"sqlite"`
	} `json:"dependencies"`
	Status ReadinessStatus `json:"status"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// EntityId defines model for EntityId.
type EntityId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// CursorExpired defines model for CursorExpired.
type CursorExpired = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// QueryChangedSinceParams defines parameters for QueryChangedSince.
type QueryChangedSinceParams struct {
	Cursor string `form:"cursor" json:"cursor"`

	// Limit Page size. Defaults to 50.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// QueryFullParams defines parameters for QueryFull.
type QueryFullParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size. Defaults to 50.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateEntityJSONRequestBody defines body for CreateEntity for application/json ContentType.
type CreateEntityJSONRequestBody = AssetEnrollmentRequest

// PatchEntityJSONRequestBody defines body for PatchEntity for application/json ContentType.
type PatchEntityJSONRequestBody = AssetReport

// CheckInAssetJSONRequestBody defines body for CheckInAsset for application/json ContentType.
type CheckInAssetJSONRequestBody = AssetReport

// ReportAssetStatusJSONRequestBody defines body for ReportAssetStatus for application/json ContentType.
type ReportAssetStatusJSONRequestBody = AssetStatusReport

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetDataset Discover the current Dataset
	// (GET /dataset)
	GetDataset(w http.ResponseWriter, r *http.Request)
	// CreateEntity Enroll an Asset with deployment authorization
	// (POST /entities)
	CreateEntity(w http.ResponseWriter, r *http.Request)
	// GetEntity Read an operational Entity
	// (GET /entities/{entity_id})
	GetEntity(w http.ResponseWriter, r *http.Request, entityId EntityId)
	// PatchEntity Report changed components of the authenticated Asset
	// (PATCH /entities/{entity_id})
	PatchEntity(w http.ResponseWriter, r *http.Request, entityId EntityId)
	// CheckInAsset Check in, reporting current Asset state and contact
	// (POST /entities/{entity_id}/checkin)
	CheckInAsset(w http.ResponseWriter, r *http.Request, entityId EntityId)
	// GetAssetStatus Read an Asset's status and contact freshness
	// (GET /entities/{entity_id}/status)
	GetAssetStatus(w http.ResponseWriter, r *http.Request, entityId EntityId)
	// ReportAssetStatus Report an Asset's own operational status
	// (PATCH /entities/{entity_id}/status)
	ReportAssetStatus(w http.ResponseWriter, r *http.Request, entityId EntityId)
	// GetHealth Check process liveness
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// QueryChangedSince Replay committed changes after a Dataset-bound cursor
	// (GET /queries/changed-since)
	QueryChangedSince(w http.ResponseWriter, r *http.Request, params QueryChangedSinceParams)
	// QueryFull Load a paginated operational picture with one baseline
	// (GET /queries/full)
	QueryFull(w http.ResponseWriter, r *http.Request, params QueryFullParams)
	// GetReadiness Check required storage dependencies
	// (GET /readiness)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDataset operation middleware
func (siw *ServerInterfaceWrapper) GetDataset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDataset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEntity operation middleware
func (siw *ServerInterfaceWrapper) CreateEntity(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEntity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEntity operation middleware
func (siw *ServerInterfaceWrapper) GetEntity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entity_id" -------------
	var entityId EntityId

	err = runtime.BindStyledParameterWithOptions("simple", "entity_id", r.PathValue("entity_id"), &entityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntity(w, r, entityId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchEntity operation middleware
func (siw *ServerInterfaceWrapper) PatchEntity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entity_id" -------------
	var entityId EntityId

	err = runtime.BindStyledParameterWithOptions("simple", "entity_id", r.PathValue("entity_id"), &entityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchEntity(w, r, entityId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckInAsset operation middleware
func (siw *ServerInterfaceWrapper) CheckInAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entity_id" -------------
	var entityId EntityId

	err = runtime.BindStyledParameterWithOptions("simple", "entity_id", r.PathValue("entity_id"), &entityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckInAsset(w, r, entityId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAssetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAssetStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entity_id" -------------
	var entityId EntityId

	err = runtime.BindStyledParameterWithOptions("simple", "entity_id", r.PathValue("entity_id"), &entityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetStatus(w, r, entityId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportAssetStatus operation middleware
func (siw *ServerInterfaceWrapper) ReportAssetStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entity_id" -------------
	var entityId EntityId

	err = runtime.BindStyledParameterWithOptions("simple", "entity_id", r.PathValue("entity_id"), &entityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportAssetStatus(w, r, entityId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueryChangedSince operation middleware
func (siw *ServerInterfaceWrapper) QueryChangedSince(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params QueryChangedSinceParams

	// ------------- Required query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueryChangedSince(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueryFull operation middleware
func (siw *ServerInterfaceWrapper) QueryFull(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params QueryFullParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueryFull(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readiness", wrapper.GetReadiness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/dataset", wrapper.GetDataset)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/entities", wrapper.CreateEntity)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/entities/{entity_id}", wrapper.GetEntity)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/entities/{entity_id}", wrapper.PatchEntity)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/entities/{entity_id}/status", wrapper.GetAssetStatus)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/entities/{entity_id}/status", wrapper.ReportAssetStatus)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/entities/{entity_id}/checkin", wrapper.CheckInAsset)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/queries/full", wrapper.QueryFull)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/queries/changed-since", wrapper.QueryChangedSince)

	return m
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type CursorExpiredJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type GetDatasetRequestObject struct {
}

type GetDatasetResponseObject interface {
	VisitGetDatasetResponse(w http.ResponseWriter) error
}

type GetDataset200JSONResponse Dataset

func (response GetDataset200JSONResponse) VisitGetDatasetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDataset401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetDataset401JSONResponse) VisitGetDatasetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDataset403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetDataset403JSONResponse) VisitGetDatasetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEntityRequestObject struct {
	Body *CreateEntityJSONRequestBody
}

type CreateEntityResponseObject interface {
	VisitCreateEntityResponse(w http.ResponseWriter) error
}

type CreateEntity200JSONResponse AssetEnrollmentResult

func (response CreateEntity200JSONResponse) VisitCreateEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEntity201JSONResponse AssetEnrollmentResult

func (response CreateEntity201JSONResponse) VisitCreateEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEntity400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateEntity400JSONResponse) VisitCreateEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEntity401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateEntity401JSONResponse) VisitCreateEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEntity403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateEntity403JSONResponse) VisitCreateEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEntity409JSONResponse struct{ ConflictJSONResponse }

func (response CreateEntity409JSONResponse) VisitCreateEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetEntityRequestObject struct {
	EntityId EntityId `json:"entity_id"`
}

type GetEntityResponseObject interface {
	VisitGetEntityResponse(w http.ResponseWriter) error
}

type GetEntity200JSONResponse Entity

func (response GetEntity200JSONResponse) VisitGetEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetEntity401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetEntity401JSONResponse) VisitGetEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetEntity403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetEntity403JSONResponse) VisitGetEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetEntity404JSONResponse struct{ NotFoundJSONResponse }

func (response GetEntity404JSONResponse) VisitGetEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchEntityRequestObject struct {
	EntityId EntityId `json:"entity_id"`
	Body     *PatchEntityJSONRequestBody
}

type PatchEntityResponseObject interface {
	VisitPatchEntityResponse(w http.ResponseWriter) error
}

type PatchEntity200JSONResponse Entity

func (response PatchEntity200JSONResponse) VisitPatchEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchEntity400JSONResponse struct{ BadRequestJSONResponse }

func (response PatchEntity400JSONResponse) VisitPatchEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PatchEntity401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PatchEntity401JSONResponse) VisitPatchEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PatchEntity403JSONResponse struct{ ForbiddenJSONResponse }

func (response PatchEntity403JSONResponse) VisitPatchEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PatchEntity404JSONResponse struct{ NotFoundJSONResponse }

func (response PatchEntity404JSONResponse) VisitPatchEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchEntity409JSONResponse struct{ ConflictJSONResponse }

func (response PatchEntity409JSONResponse) VisitPatchEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CheckInAssetRequestObject struct {
	EntityId EntityId `json:"entity_id"`
	Body     *CheckInAssetJSONRequestBody
}

type CheckInAssetResponseObject interface {
	VisitCheckInAssetResponse(w http.ResponseWriter) error
}

type CheckInAsset200JSONResponse Entity

func (response CheckInAsset200JSONResponse) VisitCheckInAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CheckInAsset400JSONResponse struct{ BadRequestJSONResponse }

func (response CheckInAsset400JSONResponse) VisitCheckInAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CheckInAsset401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CheckInAsset401JSONResponse) VisitCheckInAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CheckInAsset403JSONResponse struct{ ForbiddenJSONResponse }

func (response CheckInAsset403JSONResponse) VisitCheckInAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CheckInAsset404JSONResponse struct{ NotFoundJSONResponse }

func (response CheckInAsset404JSONResponse) VisitCheckInAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CheckInAsset409JSONResponse struct{ ConflictJSONResponse }

func (response CheckInAsset409JSONResponse) VisitCheckInAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetAssetStatusRequestObject struct {
	EntityId EntityId `json:"entity_id"`
}

type GetAssetStatusResponseObject interface {
	VisitGetAssetStatusResponse(w http.ResponseWriter) error
}

type GetAssetStatus200JSONResponse AssetStatusView

func (response GetAssetStatus200JSONResponse) VisitGetAssetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAssetStatus401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAssetStatus401JSONResponse) VisitGetAssetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAssetStatus403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAssetStatus403JSONResponse) VisitGetAssetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAssetStatus404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAssetStatus404JSONResponse) VisitGetAssetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReportAssetStatusRequestObject struct {
	EntityId EntityId `json:"entity_id"`
	Body     *ReportAssetStatusJSONRequestBody
}

type ReportAssetStatusResponseObject interface {
	VisitReportAssetStatusResponse(w http.ResponseWriter) error
}

type ReportAssetStatus200JSONResponse Entity

func (response ReportAssetStatus200JSONResponse) VisitReportAssetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReportAssetStatus400JSONResponse struct{ BadRequestJSONResponse }

func (response ReportAssetStatus400JSONResponse) VisitReportAssetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReportAssetStatus401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ReportAssetStatus401JSONResponse) VisitReportAssetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReportAssetStatus403JSONResponse struct{ ForbiddenJSONResponse }

func (response ReportAssetStatus403JSONResponse) VisitReportAssetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ReportAssetStatus404JSONResponse struct{ NotFoundJSONResponse }

func (response ReportAssetStatus404JSONResponse) VisitReportAssetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReportAssetStatus409JSONResponse struct{ ConflictJSONResponse }

func (response ReportAssetStatus409JSONResponse) VisitReportAssetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetHealth401JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetHealth403JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type QueryChangedSinceRequestObject struct {
	Params QueryChangedSinceParams
}

type QueryChangedSinceResponseObject interface {
	VisitQueryChangedSinceResponse(w http.ResponseWriter) error
}

type QueryChangedSince200JSONResponse ChangePage

func (response QueryChangedSince200JSONResponse) VisitQueryChangedSinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type QueryChangedSince400JSONResponse struct{ BadRequestJSONResponse }

func (response QueryChangedSince400JSONResponse) VisitQueryChangedSinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type QueryChangedSince401JSONResponse struct{ UnauthorizedJSONResponse }

func (response QueryChangedSince401JSONResponse) VisitQueryChangedSinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type QueryChangedSince403JSONResponse struct{ ForbiddenJSONResponse }

func (response QueryChangedSince403JSONResponse) VisitQueryChangedSinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type QueryChangedSince409JSONResponse struct{ ConflictJSONResponse }

func (response QueryChangedSince409JSONResponse) VisitQueryChangedSinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type QueryChangedSince410JSONResponse struct{ CursorExpiredJSONResponse }

func (response QueryChangedSince410JSONResponse) VisitQueryChangedSinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)
	_, err := buf.WriteTo(w)
	return err
}

type QueryFullRequestObject struct {
	Params QueryFullParams
}

type QueryFullResponseObject interface {
	VisitQueryFullResponse(w http.ResponseWriter) error
}

type QueryFull200JSONResponse EntityPage

func (response QueryFull200JSONResponse) VisitQueryFullResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type QueryFull400JSONResponse struct{ BadRequestJSONResponse }

func (response QueryFull400JSONResponse) VisitQueryFullResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type QueryFull401JSONResponse struct{ UnauthorizedJSONResponse }

func (response QueryFull401JSONResponse) VisitQueryFullResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type QueryFull403JSONResponse struct{ ForbiddenJSONResponse }

func (response QueryFull403JSONResponse) VisitQueryFullResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type QueryFull409JSONResponse struct{ ConflictJSONResponse }

func (response QueryFull409JSONResponse) VisitQueryFullResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse Readiness

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetReadiness401JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetReadiness403JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503JSONResponse Readiness

func (response GetReadiness503JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetDataset Discover the current Dataset
	// (GET /dataset)
	GetDataset(ctx context.Context, request GetDatasetRequestObject) (GetDatasetResponseObject, error)
	// CreateEntity Enroll an Asset with deployment authorization
	// (POST /entities)
	CreateEntity(ctx context.Context, request CreateEntityRequestObject) (CreateEntityResponseObject, error)
	// GetEntity Read an operational Entity
	// (GET /entities/{entity_id})
	GetEntity(ctx context.Context, request GetEntityRequestObject) (GetEntityResponseObject, error)
	// PatchEntity Report changed components of the authenticated Asset
	// (PATCH /entities/{entity_id})
	PatchEntity(ctx context.Context, request PatchEntityRequestObject) (PatchEntityResponseObject, error)
	// CheckInAsset Check in, reporting current Asset state and contact
	// (POST /entities/{entity_id}/checkin)
	CheckInAsset(ctx context.Context, request CheckInAssetRequestObject) (CheckInAssetResponseObject, error)
	// GetAssetStatus Read an Asset's status and contact freshness
	// (GET /entities/{entity_id}/status)
	GetAssetStatus(ctx context.Context, request GetAssetStatusRequestObject) (GetAssetStatusResponseObject, error)
	// ReportAssetStatus Report an Asset's own operational status
	// (PATCH /entities/{entity_id}/status)
	ReportAssetStatus(ctx context.Context, request ReportAssetStatusRequestObject) (ReportAssetStatusResponseObject, error)
	// GetHealth Check process liveness
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// QueryChangedSince Replay committed changes after a Dataset-bound cursor
	// (GET /queries/changed-since)
	QueryChangedSince(ctx context.Context, request QueryChangedSinceRequestObject) (QueryChangedSinceResponseObject, error)
	// QueryFull Load a paginated operational picture with one baseline
	// (GET /queries/full)
	QueryFull(ctx context.Context, request QueryFullRequestObject) (QueryFullResponseObject, error)
	// GetReadiness Check required storage dependencies
	// (GET /readiness)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDataset operation middleware
func (sh *strictHandler) GetDataset(w http.ResponseWriter, r *http.Request) {
	var request GetDatasetRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDataset(ctx, request.(GetDatasetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDataset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDatasetResponseObject); ok {
		if err := validResponse.VisitGetDatasetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEntity operation middleware
func (sh *strictHandler) CreateEntity(w http.ResponseWriter, r *http.Request) {
	var request CreateEntityRequestObject

	var body CreateEntityJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEntity(ctx, request.(CreateEntityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEntity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEntityResponseObject); ok {
		if err := validResponse.VisitCreateEntityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEntity operation middleware
func (sh *strictHandler) GetEntity(w http.ResponseWriter, r *http.Request, entityId EntityId) {
	var request GetEntityRequestObject

	request.EntityId = entityId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEntity(ctx, request.(GetEntityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEntity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEntityResponseObject); ok {
		if err := validResponse.VisitGetEntityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchEntity operation middleware
func (sh *strictHandler) PatchEntity(w http.ResponseWriter, r *http.Request, entityId EntityId) {
	var request PatchEntityRequestObject

	request.EntityId = entityId

	var body PatchEntityJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchEntity(ctx, request.(PatchEntityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchEntity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchEntityResponseObject); ok {
		if err := validResponse.VisitPatchEntityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CheckInAsset operation middleware
func (sh *strictHandler) CheckInAsset(w http.ResponseWriter, r *http.Request, entityId EntityId) {
	var request CheckInAssetRequestObject

	request.EntityId = entityId

	var body CheckInAssetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CheckInAsset(ctx, request.(CheckInAssetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckInAsset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CheckInAssetResponseObject); ok {
		if err := validResponse.VisitCheckInAssetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAssetStatus operation middleware
func (sh *strictHandler) GetAssetStatus(w http.ResponseWriter, r *http.Request, entityId EntityId) {
	var request GetAssetStatusRequestObject

	request.EntityId = entityId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAssetStatus(ctx, request.(GetAssetStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAssetStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAssetStatusResponseObject); ok {
		if err := validResponse.VisitGetAssetStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReportAssetStatus operation middleware
func (sh *strictHandler) ReportAssetStatus(w http.ResponseWriter, r *http.Request, entityId EntityId) {
	var request ReportAssetStatusRequestObject

	request.EntityId = entityId

	var body ReportAssetStatusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReportAssetStatus(ctx, request.(ReportAssetStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReportAssetStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReportAssetStatusResponseObject); ok {
		if err := validResponse.VisitReportAssetStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// QueryChangedSince operation middleware
func (sh *strictHandler) QueryChangedSince(w http.ResponseWriter, r *http.Request, params QueryChangedSinceParams) {
	var request QueryChangedSinceRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.QueryChangedSince(ctx, request.(QueryChangedSinceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "QueryChangedSince")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(QueryChangedSinceResponseObject); ok {
		if err := validResponse.VisitQueryChangedSinceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// QueryFull operation middleware
func (sh *strictHandler) QueryFull(w http.ResponseWriter, r *http.Request, params QueryFullParams) {
	var request QueryFullRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.QueryFull(ctx, request.(QueryFullRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "QueryFull")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(QueryFullResponseObject); ok {
		if err := validResponse.VisitQueryFullResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fx7cxs3cP8qmGtm3M6cKEp+1Jb+Uiw70dRpXCtpZyqqNHi3JBHjgDOAk0xr+N07WOCePPLuaElxMvnL",
	"pghgF/vCbxcL3gWRTFIpQBgdnNwFKVU0AQMKP70RhpnVRWz/z0RwEqTULIMwEDSB4CQA/HrK4iAMFHzO",
	"mII4ODEqgzDQ0RISaifOpUqoCU6CLMORZpXaydooJhbBeh0G71jCjB0ag44USw2Tlth7ugCi2VcYkXOY",
	"04wbTYwkz8ejIHTsfM5ArUp+OK5TpZ3QLyzJkuDkaDwOg4QJ/6ngggkDC1DB2vKhQKdSaMC9/0jjD/A5",
	"A42cRVIYEPhfmqacRdQyefiHtpzeVSj+oGAenAT/cljK9dB9qw/fKCU9qfpOf1sCUY4YiSVoIqQhCTXR",
	"kpglEJmCQnpPNHFrEamIyjjoUbAOg9dSzDmLHpnRyFPV5JaZJaFEgaFMQExY7CwjJFLFoCyzdhtRphQI",
	"Q86poRqMYz1TWqo3X1JnO4/Dv2czWlKxAMLlgghJuBQLUCSSN6A0MUumLcNaqlPCJY0JJQJuiRY01Uvp",
	"mH8r1YzFMYjHYTxSgIKl/Ikmn5iISUJXaCoR5dyxXJgKMvif0ryVmXg0wWqZqQhKE4YvTDtR/S5oZpZS",
	"sa+PoeZfmNZMLKzhZeKTkLeiIrwRxhy/hiVxpjWY1zJJMuH50K9zYshgHDP7V8rfKytfw2yEmFOuIQzS",
	"yp/uAs7Ep6k21EAX73V6gQs/eQi9qi50XQQrOfsDImPFmbPsVn1vI8VATpdAuVl2cYl0fsahjoiVnKEm",
	"071mXghmJX7pZqzDwACHBIxa9Zr+Wz7a0153SkIPlEJU10IfprYZyjocLtPmbGVmQE3fBdzo2hoDdOOU",
	"Upu9p3YqazSs2LMTNuVc3exW834jlOQ8AWEq5/AA3VLOnH/XY8Pvgn3OgNBISa0JIhwGOiRsIaRFJCSi",
	"GizCSOiXdyAWVqFHxy8RPRSfQ4uEDCi74GRyuYlq3JapiKcJFWzuuWcGEt0nMlARX2ZpKhWKI6FfLtzM",
	"F88KSlQpuvKEKsbf1ycrLmPXKKLjpsBsaMeZTzSpR9KQpApSqiAmVMTlwTpb4Xl/ef4fZAZzqQA/zpnS",
	"hlixJamxAi5F+H/UcKqn1FKZXp0d/C89+Do+eDU9uL579nT9Q5t4YwciLPjsxphh0HOYPVXtQBAWJl4F",
	"yFHFRMuRHgX1pa+zmfvb3bfZVcPBKlLAPdb48tupabeXt+mMD3Y2FFTXeY2osG5vfQWYKiYilvad0JCT",
	"Y6+xSpONrbJpButhopmhRlfTFFTkZxfMxzKbcXDBpi1RGRcsiSyZYZ5S31hz8Y499EMKdf//ACmnEWii",
	"jbSu7k65UyIyzknEgSpNGDq0/Qu1+/E54Hcqh+a5ORDiUW2mGhzoLzdADRwYlkCLGHabZrneVp43Q/YD",
	"Y719McV94b06otgplMuCuwECuaE8gwEoaUNpboGtCvsAeHQP87NfhT9nD6RiCyaoKXLUETkjcwV6SRSu",
	"TBREUsXa5uCGRobADQhMwydCSFJuZkQcK5rYLGtFmCBMRAoopkfanhUiApemn9oEDkRsv6ET4SldnLv0",
	"3p7gmiZA5tSm/ApMpoSu5fUuvI/Ie1zHTETJB0lALYAwYWQeRqQATf5VAxCg0ZKkWO1wsv+304n42MRP",
	"H+3eXSBCXtwq+bejiQjawP33iMAaedtwMONU0xt6eC3XBjNhXjwLOkpiO7BGyUKFwFZ/KJ00B1Y+LcdC",
	"Hvox+2rZtQvTeBWEwSzTK8SImQZLBDDXt9FIpinErZisNa8ZFhncviCe0paC5P8sQZDXFs/SKILU+qc1",
	"RU4NaENcnPQe6o/HTBjGcRDy5r/Ufqw9M/c5QcL7CmBhbb8d6usZ1Ory/D4te49EeQ93KKh0CPa/Gdz+",
	"2XWLP7XycJ9VgxYMMewYfkcNM1kMmNJyKRb+kwKiszTlzHq9XIBZgho5O6uuebRZhnDrTZN2xNvAtbhJ",
	"ewZPY1hgxPwS8UyzG/glh8YuJuzAzk9f7MbOYcD9JjtA+KvqOgevWlfKJdSF51/W1sKPG4vpFCCeJqne",
	"stjOdKDDHvZJfTySIXMGPNY5AMmxB8ZQjXZSzYWoG+5OgImY+9uP26XkUEKzYjTnpEDJI3I2N6AQLTGx",
	"CCeCt1tjkmlDZkBm0ixJ6rmUyn2mM/vRIaLdKVmXbW45hx7UVjtp7m273St/gy13Lj7AtjvWarP115gn",
	"vKcLGHqS4ETdGxs7kO/IBesWLIx3ZpvYyV30EYr27VCTNj6NKPKc0N3YuA8xubV4y8ZZF36FFFiY/bZa",
	"4K5jPBdGsY22Y6aRHQwUNxURcE6dVO7y1WdScqCiWjd2m6nUSK/owdfrK18Zvb4bhy+2lUargq/VG4+f",
	"v2gtrcmFAq3b+bGKjzNux1ZtJAfynzPIEKCzJIGY1S+sShplAnWMtu4/HDUMKAwyLM/7r635NxVWkU+N",
	"uW2qqsOknO0lWyynMyriWxZjS4OrkVgOYlgoGuOe5HzOmWjfkb/FHqj/nsj2VjFj46oCDlRDRTNbzBiX",
	"ac5qE8k5pCBiENFqMynLc69M0BvKXAhq27qv4+55HdOZ3DgvnFbRfT2WXBZ1i7krQMgkYaYslxCzpIak",
	"SsZZhDkacxkX1BKufonCPRYR7qtsoL+H+4/KhUZ3tgpK58Foz3pD9TrDWVLJQk2SLRorGdi0rTYXqR1x",
	"D5ruQuFI/a5NmuqJFNiAGwZZGm+LvHlXRv8U3I/P1ZsT88xeP1aJqZJH13mq76kwiw3+mhrdAx3NqAY8",
	"ATbxjIs0kYc1xhUlfXfQE03ymacua1iRuZIJYaaJgFK6aAc1+QLTfsIdtwWvfcyRDQaDbbFNwBczLbHg",
	"AAxWiLxNBBUeW/WMRcKhpZS47XwNgwS09hazm31coRzfxthbgPgsM0vLfVSAvyGnZ8qmn2DVdn/ccfPp",
	"J27jaq8wFxWThqQKW1ODuit5/2A6v/xoM9VmcPIcXXeJIz8w3PCdON9K5yea7mlOBWNIYAq+w/G6x14W",
	"NO2/EUtuG/c/A+dyKP/9lOTjXTYrxpBUMmFOCdyAWmFNXHlgRpgmMXB2Awri0T00c3xDRGzKeoki6ivt",
	"erLoJNVx//Fzcfc6QAl6A5pTK75uPncUnD9gqcaneUMgTZ4w5JGo/1RHvPMU2UhJrIo/c9bdRLk5sykP",
	"t0xYsNImGb1nIrStbF2T2CZBNOAoU8ysLu0+Gg00dbc7EwSwMwfirU1YM5mJmBhJmPENbStycT7KG+Ex",
	"nweqQJW+tDQmdSd+3vWzSfocUi5X9jtSDiO+jdesiAOf2O3FZUQ50WCydEQuDPYlS8FXfqLjXPfiyDUw",
	"t0Wgs9i6tjaKGnZT7YYmTOtsgxFskQds5171oGzVwsRctjxDyGacReTMcKrd7V/RZK1HEzERbzDiFW3x",
	"VCkGmkhR45Fq8vHMt0Dj3BPyIzJCJtl4/DT6BCv8D3wckTc0Wk5EbiTuUhzIDLi8JYImoAl1/d9yjq3f",
	"oE4JFSVbhDNt3DW5HaYnAhNiqxXsFGdm5DaiAL2CUJLs6ph2HQDPxkdYhaaTzQFybhnIhCUMsWPOT3rq",
	"CtGGGZshBk6M75U0MpK8kpudBOPR0WjsbUDQlAUnwdPRePTUtQou0U0O47LssnD/FNu+iIOT4CcweWWm",
	"8aDjeDy+t87znERL7/nr+iuH4jEEys5XaIiv0GBr/LPx0TZyBf+Htf55nPS0e1L5PqEadIKTq7uKm11d",
	"r8O7WiBwf/EB6ep6fW1T7SShamWjAtPoU20vOpDMYTWLSKU27R2lubtcnKNgfMsL9+0lTmjzFXpRyduI",
	"nLlnMUwsJkKBQb/b7ERxl+1ogMfj8SnJC8pu8UzEnn9NE7DrOFak8hMvzovHLc546yb2GgOfz32Kjssf",
	"Zby6N/va0gC9rp85WB59QCtvbwxte2/hdVI9KFA7py1qYboo+6P9Hzv7f1yOHSv50er9cNztUpVXYY/l",
	"unbGq+4ZxSOwDV9v+HbNnZ2sbPCu+Excnvy0emTV/fvwrnj/t94VjgtHqb4tvGrfTjnksHh7aBl+MBPP",
	"Kxjb47jvantUdT/rnlE87eoM7VsCuc0HaqiBclLWc9L8trzZo8hXlXYmZjTwOQIL1wHjsMvOXsVTosHP",
	"dx1FZC6V7w/0TxqbARev7u/HjB4oVPveqEeOz32Nt1Jz9Gr63uPdIAf45gC51UPQPHPwUOlm9fdOtKzo",
	"5enZ9hB5GC0h+sREFRY1cIUdcCHO8rcK/9j5P3b+GHaOdkeYCL3U8BFcDbLh5SnidB/Ed5h5WU3ZBgiq",
	"XZXfJypoNmfusDy33ZDUexWrsvr7Qoe8IOU7nyt7dggAq43fAib2fLxAhr9dQBY2kYdj4B4N9oHicq1D",
	"+7uLzl64/8Ti3pij4lzyto7RdVnpPpwD/pqC/W/5xmtb2PU3EQ9oCZ5CmyVIBTbx16BuXP0L9av/ggUw",
	"d1qmSkagNeHsBlyYs0r4nIGy56GHjAea+VuqVp38VwbKX4/Gl8xdbzeCS9uv3BT3Ttt/cqdyRfz86Ljl",
	"4qIzbLmf5HnQQ7bSstpqMfWeLm3Dfz3m44Hjg3ittzT5e9VzwuDZUY+t1H9KZ/+zHbtVog3xO+nSvNZ7",
	"4G6dvDHWrH+ecV4x+rpe3WVJShfYvSdF2TRD9JIq/7ov7/zIMy332wHYKzMR+W82FDdQJewv5lEFhMPc",
	"ECOrDTgT8TEf8vG0+PEHIoW/sLYUNEIQyvES0CIOnsVQiCGhMUzEJsWQaOlxiqNXER1ehWEzs4BbUG01",
	"ZYwFb63ghsWAv5jPVxqxWnz+VwGFZRS6YWLrj0f9bSu2PX31nftdqpTmr4WrOCFlkckUOARs/axorEJn",
	"VdV2gG2QoewZeECbKIm0mMQHf8aR6qU6eje652PmVs/djIff85khHKg2qDW1IYCVBVKVzoTRvYObgqY2",
	"Ull/rHU0rB05dZMHqExxf41+cnh4dPzvo/FoPDo6eTl+OQ7W1+v/DwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
