// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createAsset = `-- name: CreateAsset :exec
INSERT INTO entities (id, kind, alias, subtype, status, link_state, latitude, longitude, altitude_m, speed_mps, heading_deg, battery_percent, command_manifest, version)
VALUES (?, 'asset', ?, ?, ?, 'offline', ?, ?, ?, ?, ?, ?, ?, 1)
`

type CreateAssetParams struct {
	ID              string
	Alias           sql.NullString
	Subtype         sql.NullString
	Status          string
	Latitude        sql.NullFloat64
	Longitude       sql.NullFloat64
	AltitudeM       sql.NullFloat64
	SpeedMps        sql.NullFloat64
	HeadingDeg      sql.NullFloat64
	BatteryPercent  sql.NullFloat64
	CommandManifest string
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) error {
	_, err := q.db.ExecContext(ctx, createAsset,
		arg.ID,
		arg.Alias,
		arg.Subtype,
		arg.Status,
		arg.Latitude,
		arg.Longitude,
		arg.AltitudeM,
		arg.SpeedMps,
		arg.HeadingDeg,
		arg.BatteryPercent,
		arg.CommandManifest,
	)
	return err
}

const createRegistration = `-- name: CreateRegistration :exec
INSERT INTO asset_registrations (request_id, asset_id, facts_digest) VALUES (?, ?, ?)
`

type CreateRegistrationParams struct {
	RequestID   string
	AssetID     string
	FactsDigest []byte
}

func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, createRegistration, arg.RequestID, arg.AssetID, arg.FactsDigest)
	return err
}

const createReport = `-- name: CreateReport :exec
INSERT INTO asset_reports (report_id, asset_id, sequence, facts_digest) VALUES (?, ?, ?, ?)
`

type CreateReportParams struct {
	ReportID    string
	AssetID     string
	Sequence    int64
	FactsDigest []byte
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.db.ExecContext(ctx, createReport,
		arg.ReportID,
		arg.AssetID,
		arg.Sequence,
		arg.FactsDigest,
	)
	return err
}

const entityExists = `-- name: EntityExists :one
SELECT EXISTS (SELECT 1 FROM entities WHERE id = ?)
`

func (q *Queries) EntityExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, entityExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getEntity = `-- name: GetEntity :one
SELECT id, kind, alias, subtype, status, status_reported_at, link_state, last_seen, latitude, longitude, altitude_m, speed_mps, heading_deg, battery_percent, command_manifest, version, last_report_sequence, created_sequence, change_sequence FROM entities WHERE id = ?
`

func (q *Queries) GetEntity(ctx context.Context, id string) (Entity, error) {
	row := q.db.QueryRowContext(ctx, getEntity, id)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Alias,
		&i.Subtype,
		&i.Status,
		&i.StatusReportedAt,
		&i.LinkState,
		&i.LastSeen,
		&i.Latitude,
		&i.Longitude,
		&i.AltitudeM,
		&i.SpeedMps,
		&i.HeadingDeg,
		&i.BatteryPercent,
		&i.CommandManifest,
		&i.Version,
		&i.LastReportSequence,
		&i.CreatedSequence,
		&i.ChangeSequence,
	)
	return i, err
}

const getRegistration = `-- name: GetRegistration :one
SELECT request_id, asset_id, facts_digest FROM asset_registrations WHERE request_id = ?
`

func (q *Queries) GetRegistration(ctx context.Context, requestID string) (AssetRegistration, error) {
	row := q.db.QueryRowContext(ctx, getRegistration, requestID)
	var i AssetRegistration
	err := row.Scan(&i.RequestID, &i.AssetID, &i.FactsDigest)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT report_id, asset_id, sequence, facts_digest FROM asset_reports WHERE report_id = ?
`

func (q *Queries) GetReport(ctx context.Context, reportID string) (AssetReport, error) {
	row := q.db.QueryRowContext(ctx, getReport, reportID)
	var i AssetReport
	err := row.Scan(
		&i.ReportID,
		&i.AssetID,
		&i.Sequence,
		&i.FactsDigest,
	)
	return i, err
}

const listEntitiesAtBaseline = `-- name: ListEntitiesAtBaseline :many
SELECT id, kind, alias, subtype, status, status_reported_at, link_state, last_seen, latitude, longitude, altitude_m, speed_mps, heading_deg, battery_percent, command_manifest, version, last_report_sequence, created_sequence, change_sequence FROM entities WHERE created_sequence <= ?1 AND id > ?2 ORDER BY id LIMIT ?3
`

type ListEntitiesAtBaselineParams struct {
	Baseline sql.NullInt64
	AfterID  string
	Limit    int64
}

func (q *Queries) ListEntitiesAtBaseline(ctx context.Context, arg ListEntitiesAtBaselineParams) ([]Entity, error) {
	rows, err := q.db.QueryContext(ctx, listEntitiesAtBaseline, arg.Baseline, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Alias,
			&i.Subtype,
			&i.Status,
			&i.StatusReportedAt,
			&i.LinkState,
			&i.LastSeen,
			&i.Latitude,
			&i.Longitude,
			&i.AltitudeM,
			&i.SpeedMps,
			&i.HeadingDeg,
			&i.BatteryPercent,
			&i.CommandManifest,
			&i.Version,
			&i.LastReportSequence,
			&i.CreatedSequence,
			&i.ChangeSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordContact = `-- name: RecordContact :exec
UPDATE entities
SET last_seen = ?1, link_state = 'healthy', version = version + 1, last_report_sequence = ?2
WHERE id = ?3
`

type RecordContactParams struct {
	ReceivedAt sql.NullInt64
	Sequence   int64
	ID         string
}

func (q *Queries) RecordContact(ctx context.Context, arg RecordContactParams) error {
	_, err := q.db.ExecContext(ctx, recordContact, arg.ReceivedAt, arg.Sequence, arg.ID)
	return err
}

const setChangeSequence = `-- name: SetChangeSequence :exec
UPDATE entities SET change_sequence = ?1, created_sequence = COALESCE(created_sequence, ?1)
WHERE id = ?2
`

type SetChangeSequenceParams struct {
	Sequence int64
	ID       string
}

func (q *Queries) SetChangeSequence(ctx context.Context, arg SetChangeSequenceParams) error {
	_, err := q.db.ExecContext(ctx, setChangeSequence, arg.Sequence, arg.ID)
	return err
}

const setComponents = `-- name: SetComponents :exec
UPDATE entities
SET latitude = ?, longitude = ?, altitude_m = ?, speed_mps = ?, heading_deg = ?, battery_percent = ?, command_manifest = ?
WHERE id = ?
`

type SetComponentsParams struct {
	Latitude        sql.NullFloat64
	Longitude       sql.NullFloat64
	AltitudeM       sql.NullFloat64
	SpeedMps        sql.NullFloat64
	HeadingDeg      sql.NullFloat64
	BatteryPercent  sql.NullFloat64
	CommandManifest string
	ID              string
}

func (q *Queries) SetComponents(ctx context.Context, arg SetComponentsParams) error {
	_, err := q.db.ExecContext(ctx, setComponents,
		arg.Latitude,
		arg.Longitude,
		arg.AltitudeM,
		arg.SpeedMps,
		arg.HeadingDeg,
		arg.BatteryPercent,
		arg.CommandManifest,
		arg.ID,
	)
	return err
}

const setStatus = `-- name: SetStatus :exec
UPDATE entities SET status = ?, status_reported_at = ? WHERE id = ?
`

type SetStatusParams struct {
	Status           string
	StatusReportedAt sql.NullInt64
	ID               string
}

func (q *Queries) SetStatus(ctx context.Context, arg SetStatusParams) error {
	_, err := q.db.ExecContext(ctx, setStatus, arg.Status, arg.StatusReportedAt, arg.ID)
	return err
}
