// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type AssetBinding struct {
	AssetID      string
	PrincipalID  string
	CredentialID string
	Verifier     []byte
	Active       bool
	Revoked      bool
}

type EnrollmentAuthority struct {
	Singleton int64
	Verifier  []byte
	Revoked   bool
}

type OperatorKey struct {
	ID        string
	Verifier  []byte
	CreatedAt int64
	Revoked   bool
}
