// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const activeOperatorKeyByVerifier = `-- name: ActiveOperatorKeyByVerifier :one
SELECT id FROM operator_keys WHERE verifier = ? AND NOT revoked
`

func (q *Queries) ActiveOperatorKeyByVerifier(ctx context.Context, verifier []byte) (string, error) {
	row := q.db.QueryRowContext(ctx, activeOperatorKeyByVerifier, verifier)
	var id string
	err := row.Scan(&id)
	return id, err
}

const countOperatorKeys = `-- name: CountOperatorKeys :one
SELECT COUNT(*) FROM operator_keys
`

func (q *Queries) CountOperatorKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOperatorKey = `-- name: CreateOperatorKey :exec
INSERT INTO operator_keys (id, verifier, created_at) VALUES (?, ?, ?)
`

type CreateOperatorKeyParams struct {
	ID        string
	Verifier  []byte
	CreatedAt int64
}

func (q *Queries) CreateOperatorKey(ctx context.Context, arg CreateOperatorKeyParams) error {
	_, err := q.db.ExecContext(ctx, createOperatorKey, arg.ID, arg.Verifier, arg.CreatedAt)
	return err
}
