// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (id, submission_id, asset_id, facts_digest, command_id, destination_latitude, destination_longitude, scheduling, cancellation_supported, progress_supported, acceptance_sequence, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending')
`

type CreateTaskParams struct {
	ID                    string
	SubmissionID          string
	AssetID               string
	FactsDigest           []byte
	CommandID             string
	DestinationLatitude   float64
	DestinationLongitude  float64
	Scheduling            string
	CancellationSupported bool
	ProgressSupported     bool
	AcceptanceSequence    int64
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.SubmissionID,
		arg.AssetID,
		arg.FactsDigest,
		arg.CommandID,
		arg.DestinationLatitude,
		arg.DestinationLongitude,
		arg.Scheduling,
		arg.CancellationSupported,
		arg.ProgressSupported,
		arg.AcceptanceSequence,
	)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, submission_id, asset_id, facts_digest, command_id, destination_latitude, destination_longitude, scheduling, cancellation_supported, progress_supported, acceptance_sequence, status, progress_percent, failure_reason, cancellation_request_id, version, created_sequence, change_sequence, execution_status FROM tasks WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.AssetID,
		&i.FactsDigest,
		&i.CommandID,
		&i.DestinationLatitude,
		&i.DestinationLongitude,
		&i.Scheduling,
		&i.CancellationSupported,
		&i.ProgressSupported,
		&i.AcceptanceSequence,
		&i.Status,
		&i.ProgressPercent,
		&i.FailureReason,
		&i.CancellationRequestID,
		&i.Version,
		&i.CreatedSequence,
		&i.ChangeSequence,
		&i.ExecutionStatus,
	)
	return i, err
}

const getTaskBySubmission = `-- name: GetTaskBySubmission :one
SELECT id, submission_id, asset_id, facts_digest, command_id, destination_latitude, destination_longitude, scheduling, cancellation_supported, progress_supported, acceptance_sequence, status, progress_percent, failure_reason, cancellation_request_id, version, created_sequence, change_sequence, execution_status FROM tasks WHERE submission_id = ?
`

func (q *Queries) GetTaskBySubmission(ctx context.Context, submissionID string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskBySubmission, submissionID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.AssetID,
		&i.FactsDigest,
		&i.CommandID,
		&i.DestinationLatitude,
		&i.DestinationLongitude,
		&i.Scheduling,
		&i.CancellationSupported,
		&i.ProgressSupported,
		&i.AcceptanceSequence,
		&i.Status,
		&i.ProgressPercent,
		&i.FailureReason,
		&i.CancellationRequestID,
		&i.Version,
		&i.CreatedSequence,
		&i.ChangeSequence,
		&i.ExecutionStatus,
	)
	return i, err
}

const listAssetTasksAtBaseline = `-- name: ListAssetTasksAtBaseline :many
SELECT id, submission_id, asset_id, facts_digest, command_id, destination_latitude, destination_longitude, scheduling, cancellation_supported, progress_supported, acceptance_sequence, status, progress_percent, failure_reason, cancellation_request_id, version, created_sequence, change_sequence, execution_status FROM tasks WHERE asset_id = ?1 AND created_sequence <= ?2
AND id > ?3 ORDER BY id LIMIT ?4
`

type ListAssetTasksAtBaselineParams struct {
	AssetID  string
	Baseline int64
	AfterID  string
	Limit    int64
}

func (q *Queries) ListAssetTasksAtBaseline(ctx context.Context, arg ListAssetTasksAtBaselineParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listAssetTasksAtBaseline,
		arg.AssetID,
		arg.Baseline,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.AssetID,
			&i.FactsDigest,
			&i.CommandID,
			&i.DestinationLatitude,
			&i.DestinationLongitude,
			&i.Scheduling,
			&i.CancellationSupported,
			&i.ProgressSupported,
			&i.AcceptanceSequence,
			&i.Status,
			&i.ProgressPercent,
			&i.FailureReason,
			&i.CancellationRequestID,
			&i.Version,
			&i.CreatedSequence,
			&i.ChangeSequence,
			&i.ExecutionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignedTasks = `-- name: ListAssignedTasks :many
SELECT id, submission_id, asset_id, facts_digest, command_id, destination_latitude, destination_longitude, scheduling, cancellation_supported, progress_supported, acceptance_sequence, status, progress_percent, failure_reason, cancellation_request_id, version, created_sequence, change_sequence, execution_status FROM tasks WHERE asset_id = ?1 AND acceptance_sequence > ?2
ORDER BY acceptance_sequence LIMIT ?3
`

type ListAssignedTasksParams struct {
	AssetID       string
	AfterSequence int64
	Limit         int64
}

func (q *Queries) ListAssignedTasks(ctx context.Context, arg ListAssignedTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listAssignedTasks, arg.AssetID, arg.AfterSequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.AssetID,
			&i.FactsDigest,
			&i.CommandID,
			&i.DestinationLatitude,
			&i.DestinationLongitude,
			&i.Scheduling,
			&i.CancellationSupported,
			&i.ProgressSupported,
			&i.AcceptanceSequence,
			&i.Status,
			&i.ProgressPercent,
			&i.FailureReason,
			&i.CancellationRequestID,
			&i.Version,
			&i.CreatedSequence,
			&i.ChangeSequence,
			&i.ExecutionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, submission_id, asset_id, facts_digest, command_id, destination_latitude, destination_longitude, scheduling, cancellation_supported, progress_supported, acceptance_sequence, status, progress_percent, failure_reason, cancellation_request_id, version, created_sequence, change_sequence, execution_status FROM tasks WHERE created_sequence > ?1 ORDER BY created_sequence LIMIT ?2
`

type ListTasksParams struct {
	AfterSequence int64
	Limit         int64
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, arg.AfterSequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.AssetID,
			&i.FactsDigest,
			&i.CommandID,
			&i.DestinationLatitude,
			&i.DestinationLongitude,
			&i.Scheduling,
			&i.CancellationSupported,
			&i.ProgressSupported,
			&i.AcceptanceSequence,
			&i.Status,
			&i.ProgressPercent,
			&i.FailureReason,
			&i.CancellationRequestID,
			&i.Version,
			&i.CreatedSequence,
			&i.ChangeSequence,
			&i.ExecutionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksAtBaseline = `-- name: ListTasksAtBaseline :many
SELECT id, submission_id, asset_id, facts_digest, command_id, destination_latitude, destination_longitude, scheduling, cancellation_supported, progress_supported, acceptance_sequence, status, progress_percent, failure_reason, cancellation_request_id, version, created_sequence, change_sequence, execution_status FROM tasks WHERE created_sequence <= ?1 AND id > ?2
ORDER BY id LIMIT ?3
`

type ListTasksAtBaselineParams struct {
	Baseline int64
	AfterID  string
	Limit    int64
}

func (q *Queries) ListTasksAtBaseline(ctx context.Context, arg ListTasksAtBaselineParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksAtBaseline, arg.Baseline, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.AssetID,
			&i.FactsDigest,
			&i.CommandID,
			&i.DestinationLatitude,
			&i.DestinationLongitude,
			&i.Scheduling,
			&i.CancellationSupported,
			&i.ProgressSupported,
			&i.AcceptanceSequence,
			&i.Status,
			&i.ProgressPercent,
			&i.FailureReason,
			&i.CancellationRequestID,
			&i.Version,
			&i.CreatedSequence,
			&i.ChangeSequence,
			&i.ExecutionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAssetSequence = `-- name: NextAssetSequence :one
INSERT INTO asset_task_sequences (asset_id, last_sequence) VALUES (?, 1)
ON CONFLICT (asset_id) DO UPDATE SET last_sequence = last_sequence + 1
RETURNING last_sequence
`

func (q *Queries) NextAssetSequence(ctx context.Context, assetID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextAssetSequence, assetID)
	var last_sequence int64
	err := row.Scan(&last_sequence)
	return last_sequence, err
}

const setTaskChangeSequence = `-- name: SetTaskChangeSequence :exec
UPDATE tasks SET change_sequence = ?1, created_sequence = COALESCE(NULLIF(created_sequence, 0), ?1)
WHERE id = ?2
`

type SetTaskChangeSequenceParams struct {
	Sequence int64
	ID       string
}

func (q *Queries) SetTaskChangeSequence(ctx context.Context, arg SetTaskChangeSequenceParams) error {
	_, err := q.db.ExecContext(ctx, setTaskChangeSequence, arg.Sequence, arg.ID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = ?1, progress_percent = ?2,
    failure_reason = ?3, cancellation_request_id = ?4,
    execution_status = ?5,
    version = version + 1
WHERE id = ?6
`

type UpdateTaskStatusParams struct {
	Status                string
	ProgressPercent       sql.NullFloat64
	FailureReason         sql.NullString
	CancellationRequestID sql.NullString
	ExecutionStatus       sql.NullString
	ID                    string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus,
		arg.Status,
		arg.ProgressPercent,
		arg.FailureReason,
		arg.CancellationRequestID,
		arg.ExecutionStatus,
		arg.ID,
	)
	return err
}
