import { AsyncLocalStorage } from "node:async_hooks";

const uuidPattern = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/g;
const timePattern = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$/;
const credentialPattern = /atlas_[A-Za-z0-9_-]{43,}/g;
const cursorKeys = new Set(["cursor", "next_cursor", "baseline", "latest"]);

/**
 * Records a scenario as readable Markdown: each step with the wire exchanges
 * and observations it caused. Only allocated IDs, clock values, secrets and
 * opaque cursors are normalized.
 */
export class Transcript {
  #title;
  #steps = [];
  #current = new AsyncLocalStorage();
  #names = new Map();

  constructor(title) {
    this.#title = title;
  }

  /** Gives a nondeterministic value (an ID or a secret) a readable label. */
  name(value, label) {
    this.#names.set(value, `<${label}>`);
  }

  /** Runs one step. Concurrent steps render in the order they were started. */
  async step(title, action) {
    const step = { title, entries: [] };
    this.#steps.push(step);
    return this.#current.run(step, action);
  }

  /**
   * Runs an action without recording its exchanges, for concurrent requests
   * whose interleaving is nondeterministic. Record an aggregate observation
   * of the results instead.
   */
  async unrecorded(action) {
    return this.#current.run({ unrecorded: true, entries: [] }, action);
  }

  note(text) {
    this.#record({ kind: "note", text });
  }

  observe(label, value) {
    this.#record({ kind: "observation", label, value });
  }

  /** Records SDK traffic into the current step. */
  fetch = (input, init) => this.#exchange("SDK", input, init);

  /** Records direct Protocol requests made by the scenario itself. */
  directFetch = (input, init) => this.#exchange("direct", input, init);

  async #exchange(source, input, init) {
    const request = new Request(input, init);
    const requestBody = request.body ? await request.clone().text() : "";
    const response = await fetch(request);
    const responseBody = await response.clone().text();
    const url = new URL(request.url);
    this.#record({
      kind: "exchange",
      source,
      method: request.method,
      target: url.pathname + url.search,
      credential: request.headers.get("authorization")?.replace(/^Bearer /i, ""),
      requestBody,
      status: response.status,
      location: response.headers.get("location"),
      responseBody,
    });
    return response;
  }

  #record(entry) {
    const step = this.#current.getStore();
    if (!step) throw new Error("Transcript entries must be recorded inside a step.");
    if (!step.unrecorded) step.entries.push(entry);
  }

  render() {
    const normalizer = new Normalizer(this.#names);
    const lines = [`# ${this.#title}`, "", "<!-- Generated by tests/e2e. Regenerate with ATLAS_E2E_UPDATE=1; review every change. -->"];
    this.#steps.forEach((step, index) => {
      lines.push("", `## ${index + 1}. ${step.title}`);
      for (const entry of step.entries) lines.push("", ...renderEntry(entry, normalizer));
    });
    return lines.join("\n") + "\n";
  }
}

function renderEntry(entry, normalizer) {
  if (entry.kind === "note") return [entry.text];
  if (entry.kind === "observation") return [`Observed ${entry.label}:`, ...json(normalizer.value(entry.value))];
  const credential = entry.credential ? normalizer.string(entry.credential) : "no credential";
  const lines = [`${entry.source} \`${entry.method} ${normalizer.target(entry.target)}\` with ${credential}`];
  if (entry.requestBody) lines.push(...body(entry.requestBody, normalizer));
  const location = entry.location ? ` · Location \`${normalizer.string(entry.location)}\`` : "";
  lines.push("", `→ **${entry.status}**${location}`);
  if (entry.responseBody) lines.push(...body(entry.responseBody, normalizer));
  return lines;
}

function body(text, normalizer) {
  try {
    return json(normalizer.value(JSON.parse(text)));
  } catch {
    return ["```text", normalizer.string(text), "```"];
  }
}

function json(value) {
  return ["```json", JSON.stringify(value, null, 2), "```"];
}

/** Replaces nondeterministic values with labels numbered by first appearance. */
class Normalizer {
  #names;
  #counters = new Map();

  constructor(names) {
    this.#names = new Map(names);
  }

  value(value, key) {
    if (Array.isArray(value)) return value.map((item) => this.value(item));
    if (value && typeof value === "object") {
      return Object.fromEntries(Object.entries(value).map(([name, item]) => [name, this.value(item, name)]));
    }
    if (typeof value !== "string") return value;
    if (cursorKeys.has(key)) return this.#label(value, "cursor");
    if (timePattern.test(value)) return "<time>";
    return this.string(value);
  }

  /** Normalizes a request path and query, labelling cursor parameters like cursor fields. */
  target(target) {
    const [path, query] = target.split("?");
    if (!query) return this.string(path);
    const params = new URLSearchParams(query);
    const labelled = [...params].map(([key, value]) => `${key}=${cursorKeys.has(key) ? this.#label(value, "cursor") : this.string(value)}`);
    return `${this.string(path)}?${labelled.join("&")}`;
  }

  string(text) {
    if (this.#names.has(text)) return this.#names.get(text);
    return text
      .replace(credentialPattern, (secret) => this.#label(secret, "credential"))
      .replace(uuidPattern, (id) => this.#label(id, "id"));
  }

  #label(value, kind) {
    if (!this.#names.has(value)) {
      const next = (this.#counters.get(kind) ?? 0) + 1;
      this.#counters.set(kind, next);
      this.#names.set(value, `<${kind}-${next}>`);
    }
    return this.#names.get(value);
  }
}
