// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const record = `-- name: Record :exec
INSERT INTO activity (actor_kind, actor_id, action, target_id, recorded_at)
VALUES (?, ?, ?, ?, ?)
`

type RecordParams struct {
	ActorKind  string
	ActorID    string
	Action     string
	TargetID   string
	RecordedAt int64
}

func (q *Queries) Record(ctx context.Context, arg RecordParams) error {
	_, err := q.db.ExecContext(ctx, record,
		arg.ActorKind,
		arg.ActorID,
		arg.Action,
		arg.TargetID,
		arg.RecordedAt,
	)
	return err
}
