// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package operationsdb

import (
	"database/sql"
)

type Activity struct {
	ID         int64
	ActorKind  string
	ActorID    string
	Action     string
	TargetID   string
	RecordedAt int64
}

type AssetChangePruned struct {
	AssetID         string
	ThroughSequence int64
}

type AssetRegistration struct {
	RequestID   string
	AssetID     string
	FactsDigest []byte
}

type AssetReport struct {
	ReportID    string
	AssetID     string
	Sequence    int64
	FactsDigest []byte
}

type AssetTaskSequence struct {
	AssetID      string
	LastSequence int64
}

type Change struct {
	Sequence     int64
	ResourceID   string
	Kind         string
	Entity       string
	ResourceType string
	Task         sql.NullString
	ScopeAssetID sql.NullString
}

type Dataset struct {
	Singleton      int64
	ID             string
	WritingRelease string
}

type Entity struct {
	ID                 string
	Kind               string
	Alias              sql.NullString
	Subtype            sql.NullString
	Status             string
	StatusReportedAt   sql.NullInt64
	LinkState          string
	LastSeen           sql.NullInt64
	Latitude           sql.NullFloat64
	Longitude          sql.NullFloat64
	AltitudeM          sql.NullFloat64
	SpeedMps           sql.NullFloat64
	HeadingDeg         sql.NullFloat64
	BatteryPercent     sql.NullFloat64
	CommandManifest    string
	Version            int64
	LastReportSequence int64
	CreatedSequence    sql.NullInt64
	ChangeSequence     int64
}

type PluginOperation struct {
	ID            string
	SubmissionID  string
	FactsDigest   []byte
	PluginID      string
	PluginRelease string
	Capability    string
	Input         string
	Status        string
	Dispatched    bool
	Output        sql.NullString
	Error         sql.NullString
	CreatedAt     int64
}

type PluginRuntime struct {
	PluginID      string
	AdmissionOpen bool
	Fault         sql.NullString
}

type Task struct {
	ID                    string
	SubmissionID          string
	AssetID               string
	FactsDigest           []byte
	CommandID             string
	DestinationLatitude   float64
	DestinationLongitude  float64
	Scheduling            string
	CancellationSupported bool
	ProgressSupported     bool
	AcceptanceSequence    int64
	Status                string
	ProgressPercent       sql.NullFloat64
	FailureReason         sql.NullString
	CancellationRequestID sql.NullString
	Version               int64
	CreatedSequence       int64
	ChangeSequence        int64
	ExecutionStatus       sql.NullString
}
