// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package operationsdb

import (
	"context"
	"database/sql"
)

const claimDispatch = `-- name: ClaimDispatch :execrows
UPDATE plugin_operations SET dispatched = TRUE WHERE id = ? AND status = 'pending' AND NOT dispatched
`

func (q *Queries) ClaimDispatch(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimDispatch, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUnfinished = `-- name: CountUnfinished :one
SELECT COUNT(*) FROM plugin_operations
WHERE plugin_id = ? AND status IN ('pending', 'in_progress', 'cancellation_requested')
`

func (q *Queries) CountUnfinished(ctx context.Context, pluginID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnfinished, pluginID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOperation = `-- name: CreateOperation :exec
INSERT INTO plugin_operations (id, submission_id, facts_digest, plugin_id, plugin_release, capability, input, status, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, 'pending', ?)
`

type CreateOperationParams struct {
	ID            string
	SubmissionID  string
	FactsDigest   []byte
	PluginID      string
	PluginRelease string
	Capability    string
	Input         string
	CreatedAt     int64
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) error {
	_, err := q.db.ExecContext(ctx, createOperation,
		arg.ID,
		arg.SubmissionID,
		arg.FactsDigest,
		arg.PluginID,
		arg.PluginRelease,
		arg.Capability,
		arg.Input,
		arg.CreatedAt,
	)
	return err
}

const getOperation = `-- name: GetOperation :one
SELECT id, submission_id, facts_digest, plugin_id, plugin_release, capability, input, status, dispatched, output, error, created_at FROM plugin_operations WHERE plugin_id = ? AND id = ?
`

type GetOperationParams struct {
	PluginID string
	ID       string
}

func (q *Queries) GetOperation(ctx context.Context, arg GetOperationParams) (PluginOperation, error) {
	row := q.db.QueryRowContext(ctx, getOperation, arg.PluginID, arg.ID)
	var i PluginOperation
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.FactsDigest,
		&i.PluginID,
		&i.PluginRelease,
		&i.Capability,
		&i.Input,
		&i.Status,
		&i.Dispatched,
		&i.Output,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getOperationBySubmission = `-- name: GetOperationBySubmission :one
SELECT id, submission_id, facts_digest, plugin_id, plugin_release, capability, input, status, dispatched, output, error, created_at FROM plugin_operations WHERE submission_id = ?
`

func (q *Queries) GetOperationBySubmission(ctx context.Context, submissionID string) (PluginOperation, error) {
	row := q.db.QueryRowContext(ctx, getOperationBySubmission, submissionID)
	var i PluginOperation
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.FactsDigest,
		&i.PluginID,
		&i.PluginRelease,
		&i.Capability,
		&i.Input,
		&i.Status,
		&i.Dispatched,
		&i.Output,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getRuntime = `-- name: GetRuntime :one
SELECT plugin_id, admission_open, fault FROM plugin_runtime WHERE plugin_id = ?
`

func (q *Queries) GetRuntime(ctx context.Context, pluginID string) (PluginRuntime, error) {
	row := q.db.QueryRowContext(ctx, getRuntime, pluginID)
	var i PluginRuntime
	err := row.Scan(&i.PluginID, &i.AdmissionOpen, &i.Fault)
	return i, err
}

const interruptAllUnfinished = `-- name: InterruptAllUnfinished :exec
UPDATE plugin_operations SET status = 'interrupted', error = ?
WHERE status IN ('pending', 'in_progress', 'cancellation_requested')
`

func (q *Queries) InterruptAllUnfinished(ctx context.Context, error sql.NullString) error {
	_, err := q.db.ExecContext(ctx, interruptAllUnfinished, error)
	return err
}

const interruptUnfinishedOf = `-- name: InterruptUnfinishedOf :exec
UPDATE plugin_operations SET status = 'interrupted', error = ?
WHERE plugin_id = ? AND status IN ('pending', 'in_progress', 'cancellation_requested')
`

type InterruptUnfinishedOfParams struct {
	Error    sql.NullString
	PluginID string
}

func (q *Queries) InterruptUnfinishedOf(ctx context.Context, arg InterruptUnfinishedOfParams) error {
	_, err := q.db.ExecContext(ctx, interruptUnfinishedOf, arg.Error, arg.PluginID)
	return err
}

const listOperationsBefore = `-- name: ListOperationsBefore :many
SELECT id, submission_id, facts_digest, plugin_id, plugin_release, capability, input, status, dispatched, output, error, created_at FROM plugin_operations
WHERE plugin_id = ?1
  AND (created_at < ?2 OR (created_at = ?2 AND id < ?3))
ORDER BY created_at DESC, id DESC
LIMIT ?4
`

type ListOperationsBeforeParams struct {
	PluginID  string
	CreatedAt int64
	ID        string
	Limit     int64
}

func (q *Queries) ListOperationsBefore(ctx context.Context, arg ListOperationsBeforeParams) ([]PluginOperation, error) {
	rows, err := q.db.QueryContext(ctx, listOperationsBefore,
		arg.PluginID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginOperation
	for rows.Next() {
		var i PluginOperation
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.FactsDigest,
			&i.PluginID,
			&i.PluginRelease,
			&i.Capability,
			&i.Input,
			&i.Status,
			&i.Dispatched,
			&i.Output,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOutcome = `-- name: SetOutcome :exec
UPDATE plugin_operations SET status = ?, output = ?, error = ? WHERE id = ?
`

type SetOutcomeParams struct {
	Status string
	Output sql.NullString
	Error  sql.NullString
	ID     string
}

func (q *Queries) SetOutcome(ctx context.Context, arg SetOutcomeParams) error {
	_, err := q.db.ExecContext(ctx, setOutcome,
		arg.Status,
		arg.Output,
		arg.Error,
		arg.ID,
	)
	return err
}

const setOutcomeFrom = `-- name: SetOutcomeFrom :execrows
UPDATE plugin_operations SET status = ?1, error = ?2
WHERE id = ?3 AND status = ?4
`

type SetOutcomeFromParams struct {
	Status   string
	Error    sql.NullString
	ID       string
	Expected string
}

func (q *Queries) SetOutcomeFrom(ctx context.Context, arg SetOutcomeFromParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setOutcomeFrom,
		arg.Status,
		arg.Error,
		arg.ID,
		arg.Expected,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRuntime = `-- name: SetRuntime :exec
INSERT INTO plugin_runtime (plugin_id, admission_open, fault) VALUES (?, ?, ?)
ON CONFLICT (plugin_id) DO UPDATE SET admission_open = excluded.admission_open, fault = excluded.fault
`

type SetRuntimeParams struct {
	PluginID      string
	AdmissionOpen bool
	Fault         sql.NullString
}

func (q *Queries) SetRuntime(ctx context.Context, arg SetRuntimeParams) error {
	_, err := q.db.ExecContext(ctx, setRuntime, arg.PluginID, arg.AdmissionOpen, arg.Fault)
	return err
}
