// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type AssetRegistration struct {
	RequestID   string
	AssetID     string
	FactsDigest []byte
}

type AssetReport struct {
	ReportID    string
	AssetID     string
	Sequence    int64
	FactsDigest []byte
}

type Change struct {
	Sequence   int64
	ResourceID string
	Kind       string
	Entity     string
}

type Dataset struct {
	Singleton      int64
	ID             string
	WritingRelease string
}

type Entity struct {
	ID                 string
	Kind               string
	Alias              sql.NullString
	Subtype            sql.NullString
	Status             string
	StatusReportedAt   sql.NullInt64
	LinkState          string
	LastSeen           sql.NullInt64
	Latitude           sql.NullFloat64
	Longitude          sql.NullFloat64
	AltitudeM          sql.NullFloat64
	SpeedMps           sql.NullFloat64
	HeadingDeg         sql.NullFloat64
	BatteryPercent     sql.NullFloat64
	CommandManifest    string
	Version            int64
	LastReportSequence int64
	CreatedSequence    sql.NullInt64
	ChangeSequence     int64
}
