// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const insertChange = `-- name: InsertChange :one
INSERT INTO changes (resource_id, kind, entity) VALUES (?, ?, ?) RETURNING sequence
`

type InsertChangeParams struct {
	ResourceID string
	Kind       string
	Entity     string
}

func (q *Queries) InsertChange(ctx context.Context, arg InsertChangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChange, arg.ResourceID, arg.Kind, arg.Entity)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const latestSequence = `-- name: LatestSequence :one
SELECT CAST(COALESCE(MAX(sequence), 0) AS INTEGER) FROM changes
`

func (q *Queries) LatestSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestSequence)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listChangesAfter = `-- name: ListChangesAfter :many
SELECT sequence, resource_id, kind, entity FROM changes WHERE sequence > ? ORDER BY sequence LIMIT ?
`

type ListChangesAfterParams struct {
	Sequence int64
	Limit    int64
}

func (q *Queries) ListChangesAfter(ctx context.Context, arg ListChangesAfterParams) ([]Change, error) {
	rows, err := q.db.QueryContext(ctx, listChangesAfter, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.Sequence,
			&i.ResourceID,
			&i.Kind,
			&i.Entity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestSequence = `-- name: OldestSequence :one
SELECT CAST(COALESCE(MIN(sequence), 0) AS INTEGER) FROM changes
`

func (q *Queries) OldestSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, oldestSequence)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneChanges = `-- name: PruneChanges :exec
DELETE FROM changes WHERE sequence <= ?
`

func (q *Queries) PruneChanges(ctx context.Context, sequence int64) error {
	_, err := q.db.ExecContext(ctx, pruneChanges, sequence)
	return err
}
